/**
 * Created by Administrator on 2017/4/8.
 */
;(function (angular) {
    angular.module('app').config(['$stateProvider','$urlRouterProvider',function ($stateProvider,$urlRouterProvider) {
        $urlRouterProvider.otherwise('app/home');
        $stateProvider.state('app',{
            url:'/app',
            views:{
                home:{
                    templateUrl:'view/home_tpl.html',
                    controller:'homeController'
                },
                past:{
                    templateUrl:'view/past_tpl.html',
                    controller:'pastController'
                },
                author:{
                    templateUrl:'view/author_tpl.html',
                    controller:'authorController'
                },
                column:{
                    templateUrl:'view/column_tpl.html',
                    controller:'columnController'
                },
                my:{
                    templateUrl:'view/iLike_tpl.html',
                    controller:'iLikeController'
                }
            }
        }).state('app.home',{
            url:'/home',
            template:'<homelist></homelist>'
        }).state('app.past',{
            url:'/past',
            template:'<homelist></homelist>'
        }).state('app.detail',{
            url:'/detail',
            template:'<detail></detail>',
        }).state('app.author',{
            url:'/author',
            templateUrl:'view/tpl/authorlist_tpl.html'
        }).state('app.authordetail',{
            url:'/authordetail',
            template:'<homelist></homelist>'
        }).state('app.column',{
            url:'/column',
            templateUrl:'view/tpl/columns_tpl.html'
        }).state('app.columndetail',{
            url:'/columndetail',
            template:'<homelist></homelist>'
        }).state('app.iLike',{
            url:'/iLike',
            template:'<homelist></homelist>'
        });
    }]);
})(angular);
